### ISSUE TITLE
the following line after `protect should not be indented 

### ISSUE THREAD

**Issue by zhuzhzh** [thomasrussellmurphy/istyle-verilog-formatter#6] opened 2018-06-15 07:05 UTC
The test is 
```verilog
    module test (); 
    
    `protect
    
    assign a = b;
    assign a = b;
    
    `endprotect
    // pragma protect end
    endmodule
```

the output of `iStyle test.sv` is 
```verilog
module test ();

`protect

    assign a = b;
assign a = b;

`endprotect
    // pragma protect end
    endmodule
```

**Comment by thomasrussellmurphy** [comment] 2018-06-15 13:46
This looks like a duplicate of #4, just with different compiler directives. Please also note that `iStyle` likely does not support SystemVerilog specific syntax properly.

**Comment by RPGP1** [comment] 2019-04-23 10:14
The problem seems to occur if unregistered preprocessor commands are used in the script.
Although I do not understand how iStyle works, my attempt to add new members to ASResource worked.

**Closed** 2020-04-26 02:16 UTC
